name = "NoiSuntemMinecraft2"
author = "Vlad"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd216d795b3c6d6deb93ad03a166edd6197f068c50114de7ed2d673b21a797a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
