name = "NoiSuntemMinecraft2"
author = "Vlad"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5891a218c79c1986053c2048d73abffa05884bdaec7f93cfb77cd1b28d5323c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
